# Generated by Django 4.2.8 on 2024-01-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='previous_modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последнего входа'),
        ),
    ]
