# Generated by Django 4.2.7 on 2023-11-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='telegram chat id'),
        ),
    ]
