# Generated by Django 4.2.7 on 2023-11-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='имя'),
        ),
    ]
