# Generated by Django 4.2.8 on 2023-12-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='название')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/', verbose_name='превью')),
                ('description', models.TextField(verbose_name='описание')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
    ]
