# Generated by Django 4.2.8 on 2024-01-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='previous_modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='предыдущая дата обновления'),
        ),
    ]
