# Generated by Django 4.2.8 on 2023-12-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления'),
        ),
    ]
