# Generated by Django 5.0 on 2023-12-09 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.TimeField()),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('is_pleasurable', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('each hour', 'каждый час'), ('daily', 'Раз в день'), ('weekly', 'Раз в неделю')], default='weekly', max_length=50)),
                ('reward', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_time', models.IntegerField()),
                ('is_public', models.BooleanField(blank=True, default=False, null=True)),
                ('habit_date', models.DateField()),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit')),
            ],
        ),
    ]
