# Generated by Django 4.2.7 on 2023-11-07 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.TimeField()),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('is_pleasurable', models.BooleanField(default=False)),
                ('frequency', models.IntegerField(blank=True, default=1, null=True)),
                ('reward', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_time', models.IntegerField()),
                ('is_public', models.BooleanField(blank=True, default=False, null=True)),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
