# Generated by Django 4.2.7 on 2023-11-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('each hour', 'каждый час'), ('daily', 'Раз в день'), ('weekly', 'Раз в неделю')], default='weekly', max_length=50),
        ),
    ]
