version: '3'

services:

  redis:
    image: redis
    ports:
      - '6380:6380'

  db:
    image: postgres
    environment:
      - POSTGRES_DB=habits_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata


    volumes:
      - pg_data:/var/lib/postgresql/data

    ports:
      - '5433:5433'

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: True
    command: sh -c "python manage.py migrate && python manage.py  && python manage.py runserver 0.0.0.0:8000"
#    environment:
#      - DJANGO_SUPERUSER_USERNAME=pavel
#      - DJANGO_SUPERUSER_PASSWORD=123
#      - DJANGO_SUPERUSER_EMAIL=pavel@example.com
    ports:
      - '8001:8000'

    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
    tty: True
    command:  celery -A habit worker -l INFO

    depends_on:
      - redis
      - app
      - telegram


  celery_beat:
    build: .
    tty: True
    command:  celery -A habit beat -l INFO -S django

    depends_on:
      - redis
      - app
      - telegram

  telegram:
      build: .
      command: sh -c "python3 manage.py bot"

      environment:
        - TELEGRAM_TOKEN=SECRET_KEY


volumes:
  pg_data: